version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dockerize
          command: |
            echo $DISCORD_TOKEN > token.txt && \
            docker login -u $DOCKER_USER -p $DOCKER_PASS && \
            docker build -t fiendsoftheelements/ffr-bot:latest -f Dockerfile . && \
            docker push fiendsoftheelements/ffr-bot:latest

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master

